return {
  --   'goolord/alpha-nvim',
  --   dependencies = {
  --     'nvim-tree/nvim-web-devicons',
  --     'nvim-lua/plenary.nvim',
  --   },
  --   config = function()
  --     local alpha = require 'alpha'
  --     local dashboard = require 'alpha.themes.dashboard'
  --
  --     local new_dashboard_art = [[
  --                        .,,uod8B8bou,,.
  --               ..,uod8BBBBBBBBBBBBBBBBRPFT?l!i:.
  --          ,=m8BBBBBBBBBBBBBBBRPFT?!||||||||||||||
  --          !...:!TVBBBRPFT||||||||||!!^^""   ||||
  --          !.......:!?|||||!!^^""            ||||
  --          !.........||||                     ||||
  --          !.........||||  ##                 ||||
  --          !.........||||                     ||||
  --          !.........||||                     ||||
  --          !.........||||                     ||||
  --          !.........||||                     ||||
  --          `.........||||                    ,||||
  --           .;.......||||               _.-!!|||||
  --    .,uodWBBBBb.....||||       _.-!!|||||||||!:'
  -- !YBBBBBBBBBBBBBBb..!|||:..-!!|||||||!iof68BBBBBb....
  -- !..YBBBBBBBBBBBBBBbaaitf68BBBBBBRPFT?!:::::::::     `.
  -- !....YBBBBBBBBBBBBBBBBBBBRPFT?!::::::;:!^"`;:::       `.
  -- !......YBBBBBBBBBBRPFT?!::::::::::^''...::::::;         iBBbo.
  -- `..........YBRPFT?!::::::::::::::::::::::::;iof68bo.      WBBBBbo.
  --   `..........:::::::::::::::::::::::;iof688888888888b.     `YBBBP^'
  --     `........::::::::::::::::;iof688888888888888888888b.     `
  --       `......:::::::::;iof688888888888888888888888888888b.
  --         `....:::;iof68888888888888888888888888888888899fT!
  --           `..::!8888888888888888888888888888888899fT|!^"'
  --             `' !!988888888888888888888888899fT|!^"'
  --                 `!!8888888888888888899fT|!^"'
  --                   `!988888888899fT|!^"'
  --                     `!9899fT|!^"'
  --                       `!^"'
  -- ]]
  --     dashboard.section.header.val = new_dashboard_art
  --
  --     -- Set menu
  --     dashboard.section.buttons.val = {
  --       dashboard.button('e', '  > New file', ':ene <BAR> startinsert <CR>'),
  --       dashboard.button('f', '  > Find file', ':cd $HOME/Workspace | Telescope find_files<CR>'),
  --       dashboard.button('r', '  > Recent', ':Telescope oldfiles<CR>'),
  --       dashboard.button('s', '  > Settings', ':e $MYVIMRC | :cd %:p:h | split . | wincmd k | pwd<CR>'),
  --       dashboard.button('q', '  > Quit NVIM', ':qa<CR>'),
  --     }
  --
  --     -- Set footer
  --     --   NOTE: This is currently a feature in my fork of alpha-nvim (opened PR #21, will update snippet if added to main)
  --     --   To see test this yourself, add the function as a dependecy in packer and uncomment the footer lines
  --     --   ```init.lua
  --     --   return require('packer').startup(function()
  --     --       use 'wbthomason/packer.nvim'
  --     --       use {
  --     --           'goolord/alpha-nvim', branch = 'feature/startify-fortune',
  --     --           requires = {'BlakeJC94/alpha-nvim-fortune'},
  --     --           config = function() require("config.alpha") end
  --     --       }
  --     --   end)
  --     --   ```
  --     -- local fortune = require("alpha.fortune")
  --     -- dashboard.section.footer.val = fortune()
  --
  --     -- Send config to alpha
  --     alpha.setup(dashboard.opts)
  --
  --     -- Disable folding on alpha buffer
  --     vim.cmd [[autocmd FileType alpha setlocal nofoldenable]]
  --     vim.cmd [[au FileType alpha NvimTreeOpen ]]
  --   end,
}
