-- require('mini.surround').setup {
--   -- Add custom surroundings to be used on top of builtin ones. For more
--   -- information with examples, see `:h MiniSurround.config`.
--   -- custom_surroundings = nil,
--
--   -- Duration (in ms) of highlight when calling `MiniSurround.highlight()`
--   -- highlight_duration = 500,
--
--   -- Module mappings. Use `''` (empty string) to disable one.
--   mappings = {
--     add = '<C-s>', -- Add surrounding in Normal and Visual modes
--     delete = '<C-s>d', -- Delete surrounding
--     find = '<C-s>f', -- Find surrounding (to the right)
--     find_left = '<C-s>F', -- Find surrounding (to the left)
--     highlight = '<C-s>h', -- Highlight surrounding
--     replace = '<C-s>r', -- Replace surrounding
--     update_n_lines = 'snn', -- Update `n_lines`
--
--     suffix_last = 'l', -- Suffix to search with "prev" method
--     suffix_next = 'n', -- Suffix to search with "next" method
--   },
--
--   -- Number of lines within which surrounding is searched
--   n_lines = 20,
--
--   -- Whether to respect selection type:
--   -- - Place surroundings on separate lines in linewise mode.
--   -- - Place surroundings on each line in blockwise mode.
--   -- respect_selection_type = false,
--
--   -- How to search for surrounding (first inside current line, then inside
--   -- neighborhood). One of 'cover', 'cover_or_next', 'cover_or_prev',
--   -- 'cover_or_nearest', 'next', 'prev', 'nearest'. For more details,
--   -- see `:h MiniSurround.config`.
--   -- search_method = 'cover',
--
--   -- Whether to disable showing non-error feedback
--   -- silent = false,
--
--   -- mappings = {
--   --   add = 'ys',
--   --   delete = 'ds',
--   --   find = '',
--   --   find_left = '',
--   --   highlight = '',
--   --   replace = 'cs',
--   --   update_n_lines = '',
--   --
--   --   -- Add this only if you don't want to use extended mappings
--   --   suffix_last = '',
--   --   suffix_next = '',
--   -- },
--   search_method = 'cover_or_next',
-- }
--
-- return {}
--
-- -- Remap adding surrounding to Visual mode selection
-- -- vim.keymap.del('x', 'ys')
-- -- vim.keymap.set('x', 'S', [[:<C-u>lua MiniSurround.add('visual')<CR>]], { silent = true })
-- --
-- -- -- Make special mapping for "add surrounding for line"
-- -- vim.keymap.set('n', 'yss', 'ys_', { remap = true })
return {}
