-- --
-- -- AstroCommunity: import any community modules here
-- -- We import this file in `lazy_setup.lua` before the `plugins/` folder.
-- -- This guarantees that the specs are processed before any user plugins.
--
-- ---@type LazySpec
return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.colorscheme.rose-pine" },
  { import = "astrocommunity.colorscheme.catppuccin" },
  -- { import = "astrocommunity.colorscheme.bamboo-nvim" },
  -- { import = "astrocommunity.colorscheme.everforest" },
  { import = "astrocommunity.colorscheme.poimandres-nvim" },
  -- { import = "astrocommunity.colorscheme.cyberdream-nvim" },
  -- { import = "astrocommunity.colorscheme.dracula-nvim" },
  -- { import = "astrocommunity.colorscheme.night-owl-nvim" },
  { import = "astrocommunity.colorscheme.mellifluous-nvim" },
  { import = "astrocommunity.colorscheme.gruvbox-nvim" },
  -- ellisonleao/gruvbox.nvim
  -- { import = "astrocommunity.colorscheme.kanagawa-nvim" },
  -- { import = "astrocommunity.colorscheme.iceberg-vim" },
  -- { import = "astrocommunity.colorscheme.nord-nvim" },
  -- { import = "astrocommunity.colorscheme.vim-dogrun" },
  { import = "astrocommunity.color.transparent-nvim" },
  { import = "astrocommunity.syntax.vim-sandwich" },
  { import = "astrocommunity.workflow.hardtime-nvim" },
  { import = "astrocommunity.motion.harpoon" },
  { import = "astrocommunity.motion.leap-nvim" },
  { import = "astrocommunity.motion.nvim-tree-pairs" },
  { import = "astrocommunity.media.vim-wakatime" },
  { import = "astrocommunity.pack.typescript-all-in-one" },
  { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.pack.cpp" },
  { import = "astrocommunity.pack.svelte" },
  { import = "astrocommunity.pack.cmake" },
  { import = "astrocommunity.pack.html-css" },
  { import = "astrocommunity.pack.rust" },
  { import = "astrocommunity.pack.mdx" },
  { import = "astrocommunity.pack.markdown" },
  { import = "astrocommunity.pack.astro" },
  -- { import = "astrocommunity.pack.dart" },
  { import = "astrocommunity.pack.docker" },
  { import = "astrocommunity.pack.full-dadbod" },
  { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.pack.tailwindcss" },
  { import = "astrocommunity.pack.sql" },
  { import = "astrocommunity.pack.go" },
  { import = "astrocommunity.pack.xml" },
  { import = "astrocommunity.pack.toml" },
  { import = "astrocommunity.pack.swift" },
  { import = "astrocommunity.pack.cs" },
  { import = "astrocommunity.pack.java" },
  { import = "astrocommunity.pack.kotlin" },
  { import = "astrocommunity.file-explorer.oil-nvim" },
  { import = "astrocommunity.completion.supermaven-nvim" },
  -- { import = "astrocommunity.completion.avante-nvim" },
  { import = "astrocommunity.test.neotest" },
  -- { import = "astrocommunity.fuzzy-finder.fzf-lua" },
  -- { import = "astrocommunity.game.leetcode-nvim" },
  { import = "astrocommunity.recipes.disable-tabline" },
  -- { import = "astrocommunity.recipes.telescope-lsp-mappings" },
  --
  { import = "astrocommunity.recipes.telescope-nvchad-theme" },
  { import = "astrocommunity.recipes.astrolsp-no-insert-inlay-hints" },
  { import = "astrocommunity.recipes.vscode" },
  { import = "astrocommunity.lsp.lsp-signature-nvim" },
  { import = "astrocommunity.register.nvim-neoclip-lua" },
  { import = "astrocommunity.split-and-window.windows-nvim" },
  { import = "astrocommunity.utility.lua-json5" },
  { import = "astrocommunity.color.modes-nvim" },
}
